# UI Colors (extended)
accent = "#9bb9de"
cursor = "#e2cbd1"

# Primary colors
foreground = "#cfd0e6"
background = "#212130"

# Selection colors
selection_foreground = "#212130"
selection_background = "#c4b8d6"

# Normal colors (ANSI 0-7)
color0 = "#45475a"
color1 = "#dc96aa"
color2 = "#a9d3a6"
color3 = "#e7d6b1"
color4 = "#9bb9de"
color5 = "#e0bdd3"
color6 = "#9bd0c7"
color7 = "#bcc0d8"

# Bright colors (ANSI 8-15)
color8 = "#6f748b"
color9 = "#e4adbc"
color10 = "#bdddba"
color11 = "#f0e5cc"
color12 = "#b0c6e8"
color13 = "#ecd0e2"
color14 = "#afd9d2"
color15 = "#e2e3f0"
