# Background and foreground colors
background = #2c2b3b
foreground = #bcb3cc

# Standard colors
palette = 0=#2c2b3b
palette = 1=#c2a3b1
palette = 2=#abc0a5
palette = 3=#bfc2a3
palette = 4=#a4aec1
palette = 5=#bca9b8
palette = 6=#9ec7c6
palette = 7=#bcb3cc

# Bright colors
palette = 8=#656581
palette = 9=#cd98b4
palette = 10=#a8cd98
palette = 11=#c7cd98
palette = 12=#98a8cd
palette = 13=#c69fc1
palette = 14=#98cdcc
palette = 15=#bbb3cc
