background            #2c2b3b
foreground            #bcb3cc

# black
color0  #2c2b3b
color8  #656581

# red
color1  #c2a3b1
color9  #cd98b4

# green
color2  #abc0a5
color10 #a8cd98

# yellow
color3  #bfc2a3
color11 #c7cd98

# blue
color4  #a4aec1
color12 #98a8cd

# magenta
color5  #bca9b8
color13 #c69fc1

#cyan
color6  #9ec7c6
color14 #98cdcc

#white
color7  #bcb3cc
color15 #bbb3cc


